apiVersion: apps/v1
kind: Deployment
metadata:
  name: RestAPI-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: RestAPI-container
        image: yanisboumrah/RestApi:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: RestAPI-service
spec:
  selector:
    app: devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
